<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>
    <AssemblyName>TestSDK.Net48</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\YoloDeploy.SDK.Net48\YoloDeploy.SDK.Net48.csproj" />
  </ItemGroup>
</Project>
